package tn.esprit.pidev;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import tn.esprit.pidev.GUI.AfficherLivraisonForm;
import tn.esprit.pidev.GUI.AjouterLivraisonForm;
import tn.esprit.pidev.GUI.MenuForm;
import tn.esprit.pidev.Services.ServiceDepot;
import tn.esprit.pidev.Services.ServiceLivraison;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
       /* if(current != null){
            current.show();
            return;
        }*/
       // ServiceLivraison lS = new ServiceLivraison();
        //lS.Showlivraisonbyid(30);
        //Livraison l = new Livraison(new Date(), "Carte Bancaire", "400", 1,1);
       // lS.AjouterLivraison(1, l);
        //lS.SupprimerLivraison(31);
       // Livraison l = new Livraison(new Date(), "Carte Bancaire", "300", 1,1);
       //l.setId_livraison(34);
       //lS.ModifierLivraison(8,l);
        //System.out.println(lS.getLivraisons().toString());
        
        
        /******/
        
       // ServiceDepot dS = new ServiceDepot();
        //dS.Showdepotbyid(21);

       // Depot d = new Depot("Tunis", 20, "Disponible",2);
        // dS.AjouterDepot(9, d);
       // dS.SupprimerDepot(27);
       //d.setId_depot(21);
        //dS.ModifierDepot(9,d);
       // System.out.println(dS.getDepots().toString());
        //Form hi = new Form("Hi World", BoxLayout.y());
        //hi.add(new Label("Hi World"));
        //hi.show();
        
        
        
        
        //new AjouterLivraisonForm(current).show();
        new MenuForm(current).show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
